name: deploy

#监听push操作
on:
  push:
    branches:
      - cicd # 这里只配置了cicd分支，所以只有推送cicd分支才会触发以下任务
    paths-ignore: # 下列文件的变更不会触发部署
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run docs:build

      - name: Action-Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MY_ELEMENT_SECRET }}
          BRANCH: gh-pages
          publish_dir: ./docs/.vitepress/dist
          commit_message: "自动化部署"
